# Generated by Django 5.0.7 on 2024-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_expert_user_guestuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guestuser",
            old_name="guest_username",
            new_name="username",
        ),
    ]
