# Generated by Django 5.0.7 on 2024-07-19 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_guestuser_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GuestUser",
        ),
    ]
