# Generated by Django 5.0.7 on 2024-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_delete_guestuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="prompt",
            field=models.TextField(
                default="You are an expert in your field. Provide accurate and helpful information."
            ),
        ),
    ]
